version: '3'
services:
  userver-filemgr:
    container_name: userver-filemgr
    restart: unless-stopped
    build:
      context: filemgr
      dockerfile: Dockerfile
    volumes:
      - ./filemgr:/code
      - ./logs:/code/logs
      - ./tmp:/tmp
      - ./local:/storages/local
    expose:
      - 9905
    env_file:
      - ./filemgr/.env

networks:
  default:
    external:
      name: nginx-proxy
