services:
  userver-filemgr:
    container_name: userver-filemgr
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /code
    command: ["/bin/bash", "./entrypoint.sh"]
    volumes:
      - ./:/code
      - ./local:/storages/local
    env_file:
      - .env
    environment:
      MIGRATE_BIN: ${MIGRATE_BIN:-/app/main}
      APP_BIN: ${APP_BIN:-/app/main}

networks:
  default:
    name: nginx-proxy
    external: true
