# Generated by Django 4.1.7 on 2024-05-01 21:41

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='credentials',
            field=models.JSONField(encoder=json.encoder.JSONEncoder, max_length=1024, null=True, verbose_name='JSON containing the credentials used for connection'),
        ),
    ]
