
class RouteNames:
    ROUTE_STORAGE = 'filemgr.storage'
    ROUTE_STORAGE_FILE = 'filemgr.storage.file'
    ROUTE_STORAGE_FILE_DOWNLOAD = 'filemgr.storage.file.download'
    ROUTE_STORAGE_IMAGE = 'filemgr.storage.image'
    ROUTE_STORAGE_IMAGE_DOWNLOAD = 'filemgr.storage.image.download'
    ROUTE_STORAGE_MEDIA = 'filemgr.storage.media'
    ROUTE_STORAGE_TRASH = 'filemgr.storage.trash'
    ROUTE_STORAGE_UPLOAD_FILE = 'filemgr.storage.upload_file'
    ROUTE_STORAGE_UPLOAD_URL = 'filemgr.storage.upload_url'
    ROUTE_STORAGE_USER = 'filemgr.storage.user'
    ROUTE_DOC_OPENAPI = 'filemgr.docs.openapi'
    ROUTE_DOC_SWAGGER = 'filemgr.docs.swagger'
    ROUTE_DOC_REDOC = 'filemgr.docs.redoc'
